data_source my_datasource:
  type: postgres
  host: aws-0-eu-west-3.pooler.supabase.com
  username: postgres.qqehshljyphhoqsayegh
  password: Dardilly2023*
  database: postgres
  schema: public
  quote_identifiers: true
  sampler:
    samples_limit: 20
    include_tables: 
      - btob_customers
      - btoc_customers
      - example_model

soda_cloud:
  host: cloud.soda.io
  api_key_id: ${SODA_CLOUD_API_KEY}
  api_key_secret: ${SODA_CLOUD_API_SECRET}
