name: dbt + Soda Pipeline
 
on:
  pull_request
 
permissions:
  contents: read
  pull-requests: write
 
jobs:
  data_pipeline:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install protobuf==4.25.3
          pip install dbt-postgres==1.7.4  
 
           
      - name: Debug dbt profiles directory
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of the dbt directory:"
          ls -la dbt
 
      - name: Run dbt commands
        env:
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          dbt debug --profiles-dir ./dbt --project-dir ./dbt
          dbt deps --profiles-dir ./dbt --project-dir ./dbt
          dbt run --profiles-dir ./dbt --project-dir ./dbt --target dev
          
      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@main
        continue-on-error: true
        env:
         SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY }}
         SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_SECRET }}
         POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }} 
         POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
         POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        with:
          soda_library_version: v1.0.4
          data_source: my_datasource              # corrigé
          configuration: .github/soda/configuration.yml
          checks: .github/soda/checks.yml
          
      - name: Generate Custom Report
        run: |
          pip install psycopg2-binary pandas sqlalchemy==2.0.25
          python .github/scripts/custom_report.py  # Chemin à adapter
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY }}      # À vérifier
          SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_SECRET }} # À vérifier
