name: Soda Scan with dbt

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  dbt_soda_scan:
    runs-on: ubuntu-latest
    name: Run dbt and Soda Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres soda-core-postgres

      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ./
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          dbt deps
          dbt run

      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@main
        env:
          SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY }}
          SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_SECRET }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          soda_library_version: v1.0.4
          data_source: my_datasource
          configuration: ./configuration.yml
          checks: ./checks.yml
        continue-on-error: true

      - name: Comment PR results
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Résultats du scan Soda: ${{ steps.soda_scan.outcome }}
            Détails: ${{ env.SCAN_CLOUD_LINK }}
