profile columns:
  columns:
    #- "%.%"
    - btob_customers.email_contact
    - btob_customers.siret
    - btob_customers.note_risque
    - btob_customers.chiffre_affaires
    - btoc_customers.Birthday
    - btoc_customers.StreetAddress
    - btoc_customers.LastRefreshTime

checks for CA_sup_100k:
  - row_count > 0
  - avg(chiffre_affaires) > 150000

checks for btob_customers:

  # Validity Metrics (fonctionnent tous)
  - invalid_count(email_contact) = 0:   # Validity Metrics with in-check filter  
      attributes: 
        dimension: Validity
      valid format: email
      filter: ville = 'Paris'
      name: "B2B email format check for parisian customers/Vérification du format d'email B2B pour les clients parisien"

  - invalid_percent(siret) < 1%:
      attributes: 
        dimension: Validity      
      valid regex: ^\d{14}$
      name: "B2B SIRET number format check/Vérification du format du numéro SIRET - B2B"

  - invalid_count(nom_societe) = 0:
      attributes: 
        dimension: Validity
      valid min length: 2
      name: "B2B Company name length check/Vérification de la longueur du nom de l'entreprise - B2B"

  - invalid_percent(note_risque) = 0:
      attributes: 
        dimension: Validity
      valid min: 0
      valid max: 10
      name: "B2B Risk score range check/Vérification de la plage de score de risque - B2B"

  # Numeric Metrics   (fonctionnent tous)
  - avg(chiffre_affaires) > 100000: # Vérifie que le chiffre d'affaires moyen est supérieur à 100000
      attributes: 
        dimension: Accuracy
      name: "Check average revenue"
      
  - min(nombre_employes) > 0: # Vérifie que le nombre minimum d'employés est supérieur à 0
      attributes: 
        dimension: Accuracy
      name: "Check minimum employee count"

  - max(capital_social) < 10000000: # Vérifie que le capital social maximum est inférieur à 10 millions
      attributes: 
        dimension: Accuracy
      name: "Check maximum social capital"

  - sum(chiffre_affaires) > 5000000: # Vérifie que la somme des chiffres d'affaires dépasse 5 millions
      attributes: 
        dimension: Accuracy
      name: "Check total revenue"
      
      
  # Reference Check   (fonctionne) 
  - values in (email_contact) must exist in btoc_customers ("EmailAddress"):
      attributes: 
        dimension: Consistency
      name: "Vérification de correspondance des emails entre B2B et B2C"
      samples limit: 10
      
  # Cross Check    (fonctionne)
  - row_count same as btoc_customers:
      attributes: 
        dimension: Consistency
      name: "Comparaison du nombre de clients B2B et B2C"
 
  # Distribution Check  (fonctionne)
  - distribution_difference(chiffre_affaires, chiffre_affaires_dro) > 0.1:
      attributes: 
        dimension: Consistency
      name: "Vérification de la distribution du chiffre d'affaires B2B"
      method: ks 
      distribution reference file: ./distribution_reference.yml  

      
  # Failed Rows Check (fonctionnent tous)
  - failed rows:
      attributes: 
        dimension: Accuracy
      name: "Entreprises avec un chiffre d'affaires supérieur à la moyenne et un risque élevé"
      fail condition: chiffre_affaires > (SELECT AVG(chiffre_affaires) FROM btob_customers) AND note_risque > 7
      samples limit: 10
      #samples columns:
       # - nom_societe
       #- chiffre_affaires
       #- note_risque  

  - failed rows:
      attributes: 
        dimension: Accuracy      
      name: "Entreprises avec un nombre d'employés inférieur à la moyenne mais un capital social élevé"
      fail condition: nombre_employes < (SELECT AVG(nombre_employes) FROM btob_customers) AND capital_social > 500000
      samples limit: 10
      #samples columns:
       # - nom_societe
       # - nombre_employes
       # - capital_social

  # Soda Suggest
  - schema:
      attributes: 
        dimension: Timeliness
      name: "Surveillance des modifications de schéma"
      warn:
        when schema changes:
          - column delete
          - column add
          - column index change
          - column type change

  - freshness(date_creation) < 90d:
      attributes: 
        dimension: Timeliness
      name: "Fraîcheur des données (date_creation)"

  - missing_count(duns_number) = 0:
      attributes: 
        dimension: Completeness
      name: "Le numéro DUNS ne doit pas être manquant"

#  - anomaly score for row_count < default:
#      name: "Détection d'anomalies sur le nombre de lignes"

  - missing_count(id) = 0:
      attributes: 
        dimension: Completeness
      name: "L'ID ne doit pas être manquant"

  - missing_count(num_tva) = 0:
      attributes: 
        dimension: Completeness
      name: "Le numéro de TVA ne doit pas être manquant"

  - duplicate_count(siren) = 0:
      attributes: 
        dimension: Uniqueness
      name: "Pas de doublons de numéro SIREN"

  - duplicate_count(siret) = 0:
      attributes: 
        dimension: Uniqueness
      name: "Pas de doublons de numéro SIRET"

  # Template
  #- $missing_values_check:
  #    attributes: 
  #     dimension: Completeness
  #    name: "Vérification des valeurs manquantes dans la colonne nom_societe"
  #    parameters:
  #      table: btob_customers
  #      column_name: nom_societe
  #    fail: when > 0  # Échec si au moins une valeur manquante est trouvée

      
checks for btoc_customers:

  # Validity Check (fonctionnent tous)
  - invalid_count("Gender"): # Vérifie que les valeurs de Gender sont valides
      attributes: 
        dimension: Validity
      valid values:
        - "Male"
        - "Female"
        - "Other"
        - male
        - female
        - other
      name: "Check valid Gender values/Vérification des valeurs de genre valides"
      fail: when > 0
     
  - invalid_count("EmailAddress"):
      attributes: 
        dimension: Validity
      valid format: email
      name: "Email address validity check/Vérification de la validité des adresses e-mail"
      fail: when > 0

  - invalid_count("Birthday"):  # Validity Metrics with in-check filter
      attributes: 
        dimension: Validity
      valid format: date us
      name: "Birthdate validity check for cutomers with annual revenue under 350/Vérification de la validité des dates de naissance pour les clients avec un chiffre d'affaire inferieur à 350"
      fail: when > 0
      filter: chiffreaffaire < 350
     
  - invalid_count("Phone"):
      attributes: 
        dimension: Validity
      valid format: phone number
      name: "Phone number validity check/Vérification de la validité des numéros de téléphone"
      fail: when > 0

  # Numeric Metrics  (fonctionnent tous)
  - row_count > 5000:
      attributes: 
        dimension: Accuracy
      name: "Vérification du nombre total de clients B2C"
      # Vérifie que le nombre total de clients B2C est supérieur à 5000

  - duplicate_percent("EmailAddress") < 1%:
      attributes: 
        dimension: Uniqueness
      name: "Pourcentage de doublons d'adresses email - B2C"
      # S'assure que moins de 1% des adresses email sont en double

  - min(chiffreaffaire) >= 0:
      attributes: 
        dimension: Accuracy
      name: "Minimum du chiffre d'affaires - B2C"
      # Vérifie que le chiffre d'affaires minimum n'est pas négatif

  # Reference Check    (fonctionne)
  - values in ("EmailAddress") must exist in btob_customers (email_contact):
      attributes: 
        dimension: Consistency
      name: "Vérification de correspondance des emails entre B2C et B2B"
      samples limit: 15 
 
  # Cross Check    (fonctionne)
  - row_count same as btob_customers:
      attributes: 
        dimension: Consistency
      name: "Comparaison du nombre de clients B2C et B2B"
      
  # Distribution Check  (fonctionne)
  - distribution_difference(chiffreaffaire, chiffreaffaire_dro) > 0.1:
      attributes: 
        dimension: Consistency
      name: "Vérification de la distribution du chiffre d'affaires B2C"
      method: ks 
      distribution reference file: ./distribution_reference.yml    
      
  # User-defined Check (fonctionnent tous)
  - duplicate_customers = 0:
      attributes: 
        dimension: Uniqueness
      name: "Vérification des doublons de clients B2C"
      duplicate_customers query: |
        SELECT COUNT(*) as duplicate_count
        FROM (
          SELECT
            "FirstName",
            "Surname",
            "Birthday",
            COUNT(*) AS count
          FROM
            btoc_customers
          GROUP BY
            "FirstName",
            "Surname",
            "Birthday"
          HAVING
            COUNT(*) > 1
        ) as duplicates
      fail:
        when > 0
      samples limit: 10
      samples columns:
        - FirstName
        - Surname
        - Birthday    
    
  - inconsistent_customer_data = 0:
      attributes: 
        dimension: Consistency
      name: "Vérification de la cohérence des données clients B2C"
      inconsistent_customer_data query: |
        SELECT COUNT(*) as inconsistent_count
        FROM btoc_customers
        WHERE 
          -- Vérifie la cohérence entre Gender et Title
          (
            -- Pour les hommes
            (
              LOWER("Gender") ~ '^m(ale)?$' AND 
              NOT (LOWER("Title") ~ '^m(r|ister)?\.?$' OR LOWER("Title") ~ '^s(i|ir)r?\.?$')
            )
            OR
            -- Pour les femmes
            (
              LOWER("Gender") ~ '^f(emale)?$' AND 
              NOT (
                LOWER("Title") ~ '^m(rs|issus|adam)\.?$' OR 
                LOWER("Title") ~ '^ms\.?$' OR 
                LOWER("Title") ~ '^miss\.?$'
              )
            )
            OR
            -- Pour les genres non spécifiés ou autres
            (
              LOWER("Gender") NOT IN ('male', 'female', 'm', 'f') AND 
              "Gender" IS NOT NULL AND 
              "Gender" <> ''
            )
          )
          
          -- Vérifie la cohérence entre Country et CountryFull
          OR (
            ("Country" = 'US' AND "CountryFull" <> 'United States') OR
            ("Country" = 'FR' AND "CountryFull" <> 'France') OR
            ("Country" = 'ES' AND "CountryFull" <> 'Spain') OR
            ("Country" = 'DE' AND "CountryFull" <> 'Germany')
            -- Ajoutez d'autres vérifications selon vos besoins
          )
      fail:
        when > 0
      warn:
        when > 0
      samples limit: 10
      samples columns:
        - Gender
        - Title
        - Country
        - CountryFull

  
  - invalid_street_addresses = 0:
      attributes: 
        dimension: Validity
      name: "Vérification de la validité des adresses clients B2C"
      invalid_street_addresses query: |
        SELECT COUNT(*) as invalid_count
        FROM btoc_customers
        WHERE 
            -- Vérifie si l'adresse est NULL
            "StreetAddress" IS NULL
            
            -- OU vérifie que l'adresse ne commence pas par un nombre
            OR "StreetAddress" !~ '^[0-9]+'
            
            -- OU vérifie la présence de mots indésirables au début de l'adresse
            OR "StreetAddress" ~* '^(in|at|on|the)\s'
            
            -- OU vérifie que l'adresse ne correspond pas au format attendu
            OR "StreetAddress" !~ '^[0-9]+\s+[\w\s\.-]+\s+(Street|St\.?|Avenue|Ave\.?|Boulevard|Blvd\.?|Drive|Dr\.?|Road|Rd\.?|Lane|Ln\.?|Way|Place|Pl\.?|Court|Ct\.?|Circle|Cir\.?|Terrace|Ter\.?)$'
            
            -- OU vérifie que l'adresse ne dépasse pas une longueur raisonnable (par exemple, 100 caractères)
            OR LENGTH("StreetAddress") > 100
            
            -- OU vérifie la présence de caractères spéciaux non autorisés
            OR "StreetAddress" ~ '[^a-zA-Z0-9\s\,\.#-]'
      fail:
        when > 0
      warn:
        when > 0
      samples limit: 10
      samples columns:
        - StreetAddress

  # Failed Rows Check
  - failed rows:
      attributes: 
        dimension: Consistency
      name: "Clients de sexe masculin avec un titre féminin"
      fail condition: LOWER("Gender") LIKE 'm%' AND ("Title" LIKE 'Mrs.%' OR "Title" LIKE 'Ms.%' OR "Title" LIKE 'Miss.%')
      samples limit: 10

  - failed rows:
      attributes: 
        dimension: Accuracy
      name: "Clients avec un chiffre d'affaires négatif"
      fail condition: chiffreaffaire < 0
      samples limit: 10
      #samples columns:
      #  - FirstName
      #  - Surname
      #  - chiffreaffaire

  - failed rows:
      attributes: 
        dimension: Consistency
      name: "Clients nés avant 1950 avec un chiffre d'affaires élevé ou avec date de naissance invalide"
      fail condition: |
        (
          CASE 
            WHEN "Birthday" ~ '^\d{2}/\d{2}/\d{4}$' THEN 
              CAST(RIGHT("Birthday", 4) AS INTEGER) < 1950
            ELSE TRUE  -- Considère comme échec si ce n'est pas une date valide
          END
        ) AND chiffreaffaire > 10000
      samples limit: 10
      #samples columns:
      #  - FirstName
      #  - Surname
      #  - Birthday
      #  - chiffreaffaire

  # Template
  #- $missing_values_check:
  #    attributes: 
  #      dimension: Completeness
  #    name: "Vérification des valeurs manquantes dans la colonne nom_societe"
  #    parameters:
  #      table: btoc_customers
  #      column_name: chiffreaffaire
  #    fail: when > 0  # Échec si au moins une valeur manquante est trouvée
  
